import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This will scan the docs directory and auto-generate the sidebar
    },
  ],

  // Custom sidebar for the Physical AI Humanoid Robotics Textbook
  textbookSidebar: [
    {
      type: 'doc',
      id: 'books/physical-ai-humanoid-robotics-book/intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Module 1: Foundations of Physical AI and Humanoid Robotics',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-1/chapter-1',
        'books/physical-ai-humanoid-robotics-book/modules/module-1/chapter-2',
        'books/physical-ai-humanoid-robotics-book/modules/module-1/chapter-3',
        'books/physical-ai-humanoid-robotics-book/modules/module-1/chapter-4',
        'books/physical-ai-humanoid-robotics-book/modules/module-1/chapter-5',
        'books/physical-ai-humanoid-robotics-book/modules/module-1/chapter-6',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Advanced Control and Learning in Physical AI',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-2/chapter-7',
        'books/physical-ai-humanoid-robotics-book/modules/module-2/chapter-8',
        'books/physical-ai-humanoid-robotics-book/modules/module-2/chapter-9',
        'books/physical-ai-humanoid-robotics-book/modules/module-2/chapter-10',
        'books/physical-ai-humanoid-robotics-book/modules/module-2/chapter-11',
        'books/physical-ai-humanoid-robotics-book/modules/module-2/chapter-12',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Hardware and System Integration in Humanoid Robotics',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-3/chapter-13',
        'books/physical-ai-humanoid-robotics-book/modules/module-3/chapter-14',
        'books/physical-ai-humanoid-robotics-book/modules/module-3/chapter-15',
        'books/physical-ai-humanoid-robotics-book/modules/module-3/chapter-16',
        'books/physical-ai-humanoid-robotics-book/modules/module-3/chapter-17',
        'books/physical-ai-humanoid-robotics-book/modules/module-3/chapter-18',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Software Infrastructure and Development Tools',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-4/chapter-19',
        'books/physical-ai-humanoid-robotics-book/modules/module-4/chapter-20',
        'books/physical-ai-humanoid-robotics-book/modules/module-4/chapter-21',
        'books/physical-ai-humanoid-robotics-book/modules/module-4/chapter-22',
        'books/physical-ai-humanoid-robotics-book/modules/module-4/chapter-23',
        'books/physical-ai-humanoid-robotics-book/modules/module-4/chapter-24',
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Human-Robot Interaction and Social Robotics',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-5/chapter-25',
        'books/physical-ai-humanoid-robotics-book/modules/module-5/chapter-26',
        'books/physical-ai-humanoid-robotics-book/modules/module-5/chapter-27',
        'books/physical-ai-humanoid-robotics-book/modules/module-5/chapter-28',
        'books/physical-ai-humanoid-robotics-book/modules/module-5/chapter-29',
        'books/physical-ai-humanoid-robotics-book/modules/module-5/chapter-30',
      ],
    },
    {
      type: 'category',
      label: 'Module 6: Motion Control and Locomotion',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-6/chapter-31',
        'books/physical-ai-humanoid-robotics-book/modules/module-6/chapter-32',
        'books/physical-ai-humanoid-robotics-book/modules/module-6/chapter-33',
        'books/physical-ai-humanoid-robotics-book/modules/module-6/chapter-34',
        'books/physical-ai-humanoid-robotics-book/modules/module-6/chapter-35',
        'books/physical-ai-humanoid-robotics-book/modules/module-6/chapter-36',
      ],
    },
    {
      type: 'category',
      label: 'Module 7: Perception and Sensing Technologies',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-7/chapter-37',
        'books/physical-ai-humanoid-robotics-book/modules/module-7/chapter-38',
        'books/physical-ai-humanoid-robotics-book/modules/module-7/chapter-39',
        'books/physical-ai-humanoid-robotics-book/modules/module-7/chapter-40',
        'books/physical-ai-humanoid-robotics-book/modules/module-7/chapter-41',
        'books/physical-ai-humanoid-robotics-book/modules/module-7/chapter-42',
      ],
    },
    {
      type: 'category',
      label: 'Module 8: AI and Learning Systems',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-8/chapter-43',
        'books/physical-ai-humanoid-robotics-book/modules/module-8/chapter-44',
        'books/physical-ai-humanoid-robotics-book/modules/module-8/chapter-45',
        'books/physical-ai-humanoid-robotics-book/modules/module-8/chapter-46',
        'books/physical-ai-humanoid-robotics-book/modules/module-8/chapter-47',
        'books/physical-ai-humanoid-robotics-book/modules/module-8/chapter-48',
      ],
    },
    {
      type: 'category',
      label: 'Module 9: Applications and Deployment',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-9/chapter-49',
        'books/physical-ai-humanoid-robotics-book/modules/module-9/chapter-50',
        'books/physical-ai-humanoid-robotics-book/modules/module-9/chapter-51',
        'books/physical-ai-humanoid-robotics-book/modules/module-9/chapter-52',
        'books/physical-ai-humanoid-robotics-book/modules/module-9/chapter-53',
        'books/physical-ai-humanoid-robotics-book/modules/module-9/chapter-54',
      ],
    },
    {
      type: 'category',
      label: 'Module 10: Deployment, Economics, and Future Outlook',
      collapsed: true,
      items: [
        'books/physical-ai-humanoid-robotics-book/modules/module-10/chapter-55',
        'books/physical-ai-humanoid-robotics-book/modules/module-10/chapter-56',
        'books/physical-ai-humanoid-robotics-book/modules/module-10/chapter-57',
        'books/physical-ai-humanoid-robotics-book/modules/module-10/chapter-58',
        'books/physical-ai-humanoid-robotics-book/modules/module-10/chapter-59',
        'books/physical-ai-humanoid-robotics-book/modules/module-10/chapter-60',
      ],
    },
  ],
};

export default sidebars;